import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { inspect } from 'node:util';
import { readValidatedPosts } from './posts.mjs';

const cwd = process.cwd();
const postsDir = path.join(cwd, 'content/posts');
const outputDir = path.join(cwd, 'src/generated');
const outputFile = path.join(outputDir, 'posts.generated.ts');

const posts = readValidatedPosts(postsDir);
const serializedPosts = inspect(posts, {
  depth: null,
  maxArrayLength: null,
  compact: false,
  breakLength: 100,
});

const generated = `/* eslint-disable */
/* Auto-generated by scripts/build-posts.mjs. Do not edit manually. */

import type { Post } from '../lib/posts/types';

export const generatedPosts: Post[] = ${serializedPosts};
`;

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(outputFile, generated, 'utf-8');

const formatResult = spawnSync('pnpm', ['exec', 'biome', 'format', '--write', outputFile], {
  cwd,
  stdio: 'inherit',
});

if (formatResult.status !== 0) {
  throw new Error('Failed to format generated posts file');
}

console.log(`Generated posts dataset with ${posts.length} posts`);
